# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:11:15+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Leg1(BaseModel):
    destination_airport_code: str
    origin_airport_code: str
    travel_class: str


class AirtravelMultilegRequest(BaseModel):
    apiKey_l1: str
    apiKey_l2: str
    contactEmail: str
    contactFirstName: str
    contactLastName: str
    leg1: Leg1
    leg2: Leg1
    leg3: Leg1
    legs_count: str
    number_of_passengers: str
    travel_mode: str


class AirtravelCoordinatesPostRequest(BaseModel):
    apiKey_l1: str = Field(
        ...,
        description='Client Api Key',
        examples=['d95fead6-e8a6-4547-9fb9-7835101a3960'],
    )
    apiKey_l2: str = Field(
        ...,
        description='Integration Partner Api Key',
        examples=['c60f8db5-7204-4427-960d-27400c38b166'],
    )
    destination_airport_latitude: float = Field(
        ...,
        description='Destination latitude (like:  50.870752, value = -90<=x<=90)',
        examples=[24.9056],
    )
    destination_airport_longitude: float = Field(
        ...,
        description='Destination longitude (like:  4.669490, value = -180<=x<=180)',
        examples=[67.1569],
    )
    number_of_passengers: int = Field(
        ..., description='Number of passengers (like: 1, 2 ,3 )', examples=[2]
    )
    origin_airport_latitude: float = Field(
        ...,
        description='Origin latitude (like: 23.372628 value = -90<=x<=90 )',
        examples=[31.5208],
    )
    origin_airport_longitude: float = Field(
        ...,
        description='Origin longitude (like: 113.159339, value = -180<=x<=180 )',
        examples=[74.4028],
    )
    travel_class: str = Field(
        ...,
        description="Travel class can be 'First Class', 'Economy', 'Business' or 'Premium Economy'",
        examples=['Economy'],
    )
    travel_mode: str = Field(
        ...,
        description="Travel mode can be 'one way' or 'round trip'",
        examples=['round trip'],
    )


class AirtravelCoordinatesConfirmCarbonOffsetPatchRequest(BaseModel):
    carbonOffset: str = Field(
        ..., description='Confirm Carbon Offset (Value = y/n)', examples=['y']
    )
    contactEmail: Optional[str] = Field(
        None, description='Contact email', examples=['example@example.com']
    )
    contactFirstName: Optional[str] = Field(
        None, description='Contact first name', examples=['abc']
    )
    contactLastName: Optional[str] = Field(
        None, description='Contact last name', examples=['xyz']
    )
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a78ed201d88997746c91b5']
    )


class AirtravelCoordinatesConfirmPaymentPatchRequest(BaseModel):
    apiKey_l1: str = Field(
        ...,
        description='apikey_l1 (Like: d95fead6-e8a6-4247-9fb9-7835101a4560)',
        examples=['d95fead6-e8a6-4247-9fb9-7835101a4560'],
    )
    apiKey_l2: str = Field(
        ...,
        description='apikey_l2 (Like: c60f8db5-7904-4227-960d-27400c38b166)',
        examples=['c60f8db5-7904-4227-960d-27400c38b166'],
    )
    confirmPayment: str = Field(
        ..., description='Confirm Payment (Value = y/n)', examples=['y']
    )
    paymentID: int = Field(..., description='Payment Id', examples=[34567878])
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a78ed201d88997746c91b5']
    )


class AirtravelCoordinatesConfirmPlantingPatchRequest(BaseModel):
    apiKey_l1: str = Field(
        ...,
        description='apikey_l1 (Like: d95fead6-e8a6-4247-9fb9-7835101a4560)',
        examples=['d95fead6-e8a6-4247-9fb9-7835101a4560'],
    )
    apiKey_l2: str = Field(
        ...,
        description='apikey_l2 (Like: c60f8db5-7904-4227-960d-27400c38b166)',
        examples=['c60f8db5-7904-4227-960d-27400c38b166'],
    )
    confirmPlanting: str = Field(
        ..., description='Confirm Planting (Value = y/n)', examples=['y']
    )
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a78ed201d88997746c91b5']
    )


class AirtravelCoordinatesConfirmTransactionPatchRequest(BaseModel):
    confirmTransaction: str = Field(
        ..., description='Confirm Payment Of Transaction (Value = y/n)', examples=['y']
    )
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a78ed201d88997746c91b5']
    )


class AirtravelMultilegConfirmCarbonOffsetPatchRequest(BaseModel):
    carbonOffset: str = Field(
        ..., description='Confirm Carbon Offset (Value = y/n)', examples=['y']
    )
    contactEmail: Optional[str] = Field(
        None, description='Contact email', examples=['example@example.com']
    )
    contactFirstName: Optional[str] = Field(
        None, description='Contact first name', examples=['abc']
    )
    contactLastName: Optional[str] = Field(
        None, description='Contact last name', examples=['xyz']
    )
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a75c0e94c8cb95a6d0e02e']
    )


class AirtravelMultilegConfirmPaymentPatchRequest(BaseModel):
    apiKey_l1: str = Field(
        ...,
        description='apikey_l1 (Like: d95fead6-e8a6-4247-9fb9-7835101a4560)',
        examples=['d95fead6-e8a6-4247-9fb9-7835101a4560'],
    )
    apiKey_l2: str = Field(
        ...,
        description='apikey_l2 (Like: c60f8db5-7904-4227-960d-27400c38b166)',
        examples=['c60f8db5-7904-4227-960d-27400c38b166'],
    )
    confirmPayment: str = Field(
        ..., description='Confirm Payment (Value = y/n)', examples=['y']
    )
    paymentID: int = Field(..., description='Payment Id', examples=[34567878])
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a75c0e94c8cb95a6d0e02e']
    )


class AirtravelMultilegConfirmPlantingPatchRequest(BaseModel):
    apiKey_l1: str = Field(
        ...,
        description='apikey_l1 (Like: d95fead6-e8a6-4247-9fb9-7835101a4560)',
        examples=['d95fead6-e8a6-4247-9fb9-7835101a4560'],
    )
    apiKey_l2: str = Field(
        ...,
        description='apikey_l2 (Like: c60f8db5-7904-4227-960d-27400c38b166)',
        examples=['c60f8db5-7904-4227-960d-27400c38b166'],
    )
    confirmPlanting: str = Field(
        ..., description='Confirm Planting (Value = y/n)', examples=['y']
    )
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a75c0e94c8cb95a6d0e02e']
    )


class AirtravelMultilegConfirmTransactionPatchRequest(BaseModel):
    confirmTransaction: str = Field(
        ..., description='Confirm Payment Of Transaction (Value = y/n)', examples=['y']
    )
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a75c0e94c8cb95a6d0e02e']
    )


class EcommerceDeliveryPostRequest(BaseModel):
    apiKey_l1: str = Field(
        ...,
        description='Client Api Key',
        examples=['d95fead6-e8a6-4547-9fb9-7835101a3960'],
    )
    apiKey_l2: str = Field(
        ...,
        description='Integration Partner Api Key',
        examples=['c60f8db5-7204-4427-960d-27400c38b166'],
    )
    destination_airport_code: Optional[str] = Field(
        None, description='valid airport code of destination', examples=['BRU']
    )
    destination_latitude: float = Field(
        ..., description='valid latitude of destination', examples=[50.870752]
    )
    destination_longitude: float = Field(
        ..., description='valid longitude of destination', examples=[4.66949]
    )
    origin_airport_code: Optional[str] = Field(
        None, description='valid airport code of origin', examples=['KHI']
    )
    origin_latitude: float = Field(
        ..., description='valid latitude of origin', examples=[23.372628]
    )
    origin_longitude: float = Field(
        ..., description='valid longitude of origin', examples=[113.159339]
    )
    volumetric_weight: float = Field(
        ..., description="Volumetric weight' (like:2.70)", examples=[2.7]
    )
    waybill_type: str = Field(
        ...,
        description="this can be 'air only', 'road only' or 'air and road'",
        examples=['road only'],
    )


class EcommerceDeliveryConfirmCarbonOffsetPatchRequest(BaseModel):
    carbonOffset: str = Field(
        ..., description='Confirm Carbon Offset (Value = y/n)', examples=['y']
    )
    contactEmail: Optional[str] = Field(
        None, description='Contact email', examples=['example@example.com']
    )
    contactFirstName: Optional[str] = Field(
        None, description='Contact first name', examples=['abc']
    )
    contactLastName: Optional[str] = Field(
        None, description='Contact last name', examples=['xyz']
    )
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a766d401d88997746c91a0']
    )


class EcommerceDeliveryConfirmPaymentPatchRequest(BaseModel):
    apiKey_l1: str = Field(
        ...,
        description='apikey_l1 (Like: d95fead6-e8a6-4247-9fb9-7835101a4560)',
        examples=['d95fead6-e8a6-4247-9fb9-7835101a4560'],
    )
    apiKey_l2: str = Field(
        ...,
        description='apikey_l2 (Like: c60f8db5-7904-4227-960d-27400c38b166)',
        examples=['c60f8db5-7904-4227-960d-27400c38b166'],
    )
    confirmPayment: str = Field(
        ..., description='Confirm Payment (Value = y/n)', examples=['y']
    )
    paymentID: int = Field(..., description='Payment Id', examples=[34567878])
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a766d401d88997746c91a0']
    )


class EcommerceDeliveryConfirmPlantingPatchRequest(BaseModel):
    apiKey_l1: str = Field(
        ...,
        description='apikey_l1 (Like: d95fead6-e8a6-4247-9fb9-7835101a4560)',
        examples=['d95fead6-e8a6-4247-9fb9-7835101a4560'],
    )
    apiKey_l2: str = Field(
        ...,
        description='apikey_l2 (Like: c60f8db5-7904-4227-960d-27400c38b166)',
        examples=['c60f8db5-7904-4227-960d-27400c38b166'],
    )
    confirmPlanting: str = Field(
        ..., description='Confirm Planting (Value = y/n)', examples=['y']
    )
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a766d401d88997746c91a0']
    )


class EcommerceDeliveryConfirmTransactionPatchRequest(BaseModel):
    confirmTransaction: str = Field(
        ..., description='Confirm Payment Of Transaction (Value = y/n)', examples=['y']
    )
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a766d401d88997746c91a0']
    )


class RequestApiKeyPostRequest(BaseModel):
    apiKey_l1: str = Field(
        ..., description='Api Key for client', examples=['qNahlSrEaduQ']
    )
    apiKey_l2: str = Field(
        ..., description='Integration Partner Api Key', examples=['eCqMeAfaDBWG']
    )
    email: str = Field(..., description='User email', examples=['abcd@gmail.com'])
    password: int = Field(..., description='User password', examples=[234])
    userFirstName: str = Field(..., description='User first name', examples=['usman'])
    userLastName: str = Field(..., description='User last name', examples=['ch'])


class RoadDistancePostRequest(BaseModel):
    apiKey_l1: str = Field(
        ...,
        description='Client Api Key',
        examples=['d95fead6-e8a6-4547-9fb9-7835101a3960'],
    )
    apiKey_l2: str = Field(
        ...,
        description='Integration Partner Api Key',
        examples=['c60f8db5-7204-4427-960d-27400c38b166'],
    )
    travel_distance: int = Field(..., examples=[2450])
    trip_end: int = Field(
        ..., description='timestamp in epoch time (like: 1606780799)', examples=[18]
    )
    trip_start: int = Field(
        ..., description='timestamp in epoch time (like: 1604188800)', examples=[16]
    )
    vehicle_make: Optional[str] = Field(
        None,
        description="vehicle make (like: Honda, Toyota, Smart), Required only when vehicle_type is 'personal car' ",
        examples=['Honda'],
    )
    vehicle_type: str = Field(
        ...,
        description="Vehicle type can be 'personal car', 'light truck' or 'heavy-duty truck'",
        examples=['personal car'],
    )
    vehicle_year: Optional[int] = Field(
        None,
        description="vehicle year (like: 2010, 2015, 2019), Required only when vehicle_type is 'personal car' ",
        examples=[2010],
    )


class RoadDistanceConfirmCarbonOffsetPatchRequest(BaseModel):
    carbonOffset: str = Field(
        ..., description='Confirm Carbon Offset (Value = y/n)', examples=['y']
    )
    contactEmail: Optional[str] = Field(
        None, description='Contact email', examples=['example@example.com']
    )
    contactFirstName: Optional[str] = Field(
        None, description='Contact first name', examples=['abc']
    )
    contactLastName: Optional[str] = Field(
        None, description='Contact last name', examples=['xyz']
    )
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a7823401d88997746c91a7']
    )


class RoadDistanceConfirmPaymentPatchRequest(BaseModel):
    apiKey_l1: str = Field(
        ...,
        description='apikey_l1 (Like: d95fead6-e8a6-4247-9fb9-7835101a4560)',
        examples=['d95fead6-e8a6-4247-9fb9-7835101a4560'],
    )
    apiKey_l2: str = Field(
        ...,
        description='apikey_l2 (Like: c60f8db5-7904-4227-960d-27400c38b166)',
        examples=['c60f8db5-7904-4227-960d-27400c38b166'],
    )
    confirmPayment: str = Field(
        ..., description='Confirm Payment (Value = y/n)', examples=['y']
    )
    paymentID: int = Field(..., description='Payment Id', examples=[34567878])
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a7823401d88997746c91a7']
    )


class RoadDistanceConfirmPlantingPatchRequest(BaseModel):
    apiKey_l1: str = Field(
        ...,
        description='apikey_l1 (Like: d95fead6-e8a6-4247-9fb9-7835101a4560)',
        examples=['d95fead6-e8a6-4247-9fb9-7835101a4560'],
    )
    apiKey_l2: str = Field(
        ...,
        description='apikey_l2 (Like: c60f8db5-7904-4227-960d-27400c38b166)',
        examples=['c60f8db5-7904-4227-960d-27400c38b166'],
    )
    confirmPlanting: str = Field(
        ..., description='Confirm Planting (Value = y/n)', examples=['y']
    )
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a7823401d88997746c91a7']
    )


class RoadDistanceConfirmTransactionPatchRequest(BaseModel):
    confirmTransaction: str = Field(
        ..., description='Confirm Payment Of Transaction (Value = y/n)', examples=['y']
    )
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a7823401d88997746c91a7']
    )


class UrbanDeliveryPostRequest(BaseModel):
    apiKey_l1: str = Field(
        ...,
        description='Client Api Key',
        examples=['d95fead6-e8a6-4547-9fb9-7835101a3960'],
    )
    apiKey_l2: str = Field(
        ...,
        description='Integration Partner Api Key',
        examples=['c60f8db5-7204-4427-960d-27400c38b166'],
    )
    destination_latitude: float = Field(
        ...,
        description='Destination latitude (like: 50.870752, value = -90<=x<=90)',
        examples=[-89.870752],
    )
    destination_longitude: float = Field(
        ...,
        description='Destination longitude (like: 4.669490, value = -180<=x<=180)',
        examples=[179.66949],
    )
    item_count: int = Field(
        ..., description="item_count' (like:2, value = 0<x<=100)", examples=[3]
    )
    origin_latitude: float = Field(
        ...,
        description='Origin latitude (like: 23.372628, value = -90<=x<=90)',
        examples=[-89.372628],
    )
    origin_longitude: float = Field(
        ...,
        description='Origin longitude (like: 113.159339, value = -180<=x<=180)',
        examples=[-179.159339],
    )
    vehicle_type: str = Field(
        ...,
        description='Vehicle type (like: private car, motorcycle,cargo van,zero-emission)',
        examples=['PRIVATE CAR'],
    )


class UrbanDeliveryConfirmCarbonOffsetPatchRequest(BaseModel):
    carbonOffset: str = Field(
        ..., description='Confirm Carbon Offset (Value = y/n)', examples=['y']
    )
    contactEmail: Optional[str] = Field(
        None, description='Contact email', examples=['example@example.com']
    )
    contactFirstName: Optional[str] = Field(
        None, description='Contact first name', examples=['abc']
    )
    contactLastName: Optional[str] = Field(
        None, description='Contact last name', examples=['xyz']
    )
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a7875a01d88997746c91ae']
    )


class UrbanDeliveryConfirmPaymentPatchRequest(BaseModel):
    apiKey_l1: str = Field(
        ...,
        description='apikey_l1 (Like: d95fead6-e8a6-4247-9fb9-7835101a4560)',
        examples=['d95fead6-e8a6-4247-9fb9-7835101a4560'],
    )
    apiKey_l2: str = Field(
        ...,
        description='apikey_l2 (Like: c60f8db5-7904-4227-960d-27400c38b166)',
        examples=['c60f8db5-7904-4227-960d-27400c38b166'],
    )
    confirmPayment: str = Field(
        ..., description='Confirm Payment (Value = y/n)', examples=['y']
    )
    paymentID: int = Field(..., description='Payment Id', examples=[34567878])
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a7875a01d88997746c91ae']
    )


class UrbanDeliveryConfirmPlantingPatchRequest(BaseModel):
    apiKey_l1: str = Field(
        ...,
        description='apikey_l1 (Like: d95fead6-e8a6-4247-9fb9-7835101a4560)',
        examples=['d95fead6-e8a6-4247-9fb9-7835101a4560'],
    )
    apiKey_l2: str = Field(
        ...,
        description='apikey_l2 (Like: c60f8db5-7904-4227-960d-27400c38b166)',
        examples=['c60f8db5-7904-4227-960d-27400c38b166'],
    )
    confirmPlanting: str = Field(
        ..., description='Confirm Planting (Value = y/n)', examples=['y']
    )
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a7875a01d88997746c91ae']
    )


class UrbanDeliveryConfirmTransactionPatchRequest(BaseModel):
    confirmTransaction: str = Field(
        ..., description='Confirm Payment Of Transaction (Value = y/n)', examples=['y']
    )
    transaction_id: str = Field(
        ..., description='transaction_id', examples=['60a7875a01d88997746c91ae']
    )
